### ISSUE TITLE
The noise budget for loaded BFV symmetric ciphertexts

### ISSUE THREAD

**Issue by gogo9th** [encryptorion-lab/phantom-fhe#15]
Hi,

At [examples/serialization.cu:255](https://github.com/encryptorion-lab/phantom-fhe/blob/a3dc2eb4bd571b2c8ee5748bbe07ae530da9eb17/examples/serialization.cu#L255), I inserted the following line:

`cout << "Noise: " << secret_key.invariant_noise_budget(context, x_symmetric_cipher_load) << endl;`

And if I run the example code, I get this output:

`cipher noise budget is: 0`

Actually, it seems that even for the unmodified serialization.cu file, the noise budgets are all 0:

```
Testing BFV sym Enc & Dec
testing poly_modulus_degree = 4096
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 4096
|   coeff_modulus size: 109 (36 + 36 + 37) bits

68719403009 ,  68719230977 ,  137438822401 ,

|   plain_modulus: 1032193
\
cipher noise budget is: 0
Save symmetric ciphertext to file.
Load symmetric ciphertext from file.
Decode the decrypted plaintext.
testing poly_modulus_degree = 8192
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 8192
|   coeff_modulus size: 218 (43 + 43 + 44 + 44 + 44) bits

8796092858369 ,  8796092792833 ,  17592186028033 ,  17592185438209 ,  17592184717313 ,

|   plain_modulus: 1032193
\
cipher noise budget is: 0
Save symmetric ciphertext to file.
Load symmetric ciphertext from file.
Decode the decrypted plaintext.
testing poly_modulus_degree = 16384
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 16384
|   coeff_modulus size: 438 (48 + 48 + 48 + 49 + 49 + 49 + 49 + 49 + 49) bits

281474976546817 ,  281474976317441 ,  281474975662081 ,  562949952798721 ,  562949952700417 ,  562949952274433 ,  562949951979521 ,  562949951881217 ,  562949951619073 ,

|   plain_modulus: 786433
\
cipher noise budget is: 0
Save symmetric ciphertext to file.
Load symmetric ciphertext from file.
Decode the decrypted plaintext.
testing poly_modulus_degree = 32768
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 32768
|   coeff_modulus size: 881 (55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 56) bits

36028797017456641 ,  36028797014704129 ,  36028797014573057 ,  36028797014376449 ,  36028797013327873 ,  36028797013000193 ,  36028797012606977 ,  36028797010444289 ,  36028797009985537 ,  36028797005856769 ,  36028797005529089 ,  36028797005135873 ,  36028797003694081 ,  36028797003563009 ,  36028797001138177 ,  72057594037338113 ,

|   plain_modulus: 786433
\
cipher noise budget is: 0
Save symmetric ciphertext to file.
Load symmetric ciphertext from file.
Decode the decrypted plaintext.

Testing BFV asym Enc & Dec
testing poly_modulus_degree = 4096
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 4096
|   coeff_modulus size: 109 (36 + 36 + 37) bits

68719403009 ,  68719230977 ,  137438822401 ,

|   plain_modulus: 1032193
\
Save public key to file.
Load public key from file.
cipher noise budget is: 0
Save asymmetric ciphertext to file.
Load asymmetric ciphertext from file.
Decode the decrypted plaintext.
testing poly_modulus_degree = 8192
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 8192
|   coeff_modulus size: 218 (43 + 43 + 44 + 44 + 44) bits

8796092858369 ,  8796092792833 ,  17592186028033 ,  17592185438209 ,  17592184717313 ,

|   plain_modulus: 1032193
\
Save public key to file.
Load public key from file.
cipher noise budget is: 0
Save asymmetric ciphertext to file.
Load asymmetric ciphertext from file.
Decode the decrypted plaintext.
testing poly_modulus_degree = 16384
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 16384
|   coeff_modulus size: 438 (48 + 48 + 48 + 49 + 49 + 49 + 49 + 49 + 49) bits

281474976546817 ,  281474976317441 ,  281474975662081 ,  562949952798721 ,  562949952700417 ,  562949952274433 ,  562949951979521 ,  562949951881217 ,  562949951619073 ,

|   plain_modulus: 786433
\
Save public key to file.
Load public key from file.
cipher noise budget is: 0
Save asymmetric ciphertext to file.
Load asymmetric ciphertext from file.
Decode the decrypted plaintext.
testing poly_modulus_degree = 32768
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 32768
|   coeff_modulus size: 881 (55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 56) bits

36028797017456641 ,  36028797014704129 ,  36028797014573057 ,  36028797014376449 ,  36028797013327873 ,  36028797013000193 ,  36028797012606977 ,  36028797010444289 ,  36028797009985537 ,  36028797005856769 ,  36028797005529089 ,  36028797005135873 ,  36028797003694081 ,  36028797003563009 ,  36028797001138177 ,  72057594037338113 ,

|   plain_modulus: 786433
\
Save public key to file.
Load public key from file.
cipher noise budget is: 0
Save asymmetric ciphertext to file.
Load asymmetric ciphertext from file.
Decode the decrypted plaintext.

Testing BFV mul
testing poly_modulus_degree = 4096
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 4096
|   coeff_modulus size: 109 (36 + 36 + 37) bits

68719403009 ,  68719230977 ,  137438822401 ,

|   plain_modulus: 1032193
\
Save relin key to file.
Load relin key from file.
testing poly_modulus_degree = 8192
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 8192
|   coeff_modulus size: 218 (43 + 43 + 44 + 44 + 44) bits

8796092858369 ,  8796092792833 ,  17592186028033 ,  17592185438209 ,  17592184717313 ,

|   plain_modulus: 1032193
\
Save relin key to file.
Load relin key from file.
testing poly_modulus_degree = 16384
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 16384
|   coeff_modulus size: 438 (48 + 48 + 48 + 49 + 49 + 49 + 49 + 49 + 49) bits

281474976546817 ,  281474976317441 ,  281474975662081 ,  562949952798721 ,  562949952700417 ,  562949952274433 ,  562949951979521 ,  562949951881217 ,  562949951619073 ,

|   plain_modulus: 786433
\
Save relin key to file.
Load relin key from file.
testing poly_modulus_degree = 32768
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 32768
|   coeff_modulus size: 881 (55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 56) bits

36028797017456641 ,  36028797014704129 ,  36028797014573057 ,  36028797014376449 ,  36028797013327873 ,  36028797013000193 ,  36028797012606977 ,  36028797010444289 ,  36028797009985537 ,  36028797005856769 ,  36028797005529089 ,  36028797005135873 ,  36028797003694081 ,  36028797003563009 ,  36028797001138177 ,  72057594037338113 ,

|   plain_modulus: 786433
\
Save relin key to file.
Load relin key from file.

Testing BFV rotate
testing poly_modulus_degree = 4096
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 4096
|   coeff_modulus size: 109 (36 + 36 + 37) bits

68719403009 ,  68719230977 ,  137438822401 ,

|   plain_modulus: 1032193
\
Save galois key to file.
Load galois key from file.
testing poly_modulus_degree = 8192
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 8192
|   coeff_modulus size: 218 (43 + 43 + 44 + 44 + 44) bits

8796092858369 ,  8796092792833 ,  17592186028033 ,  17592185438209 ,  17592184717313 ,

|   plain_modulus: 1032193
\
Save galois key to file.
Load galois key from file.
testing poly_modulus_degree = 16384
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 16384
|   coeff_modulus size: 438 (48 + 48 + 48 + 49 + 49 + 49 + 49 + 49 + 49) bits

281474976546817 ,  281474976317441 ,  281474975662081 ,  562949952798721 ,  562949952700417 ,  562949952274433 ,  562949951979521 ,  562949951881217 ,  562949951619073 ,

|   plain_modulus: 786433
\
Save galois key to file.
Load galois key from file.
testing poly_modulus_degree = 32768
/
| Encryption parameters :
|   scheme: BFV
|   poly_modulus_degree: 32768
|   coeff_modulus size: 881 (55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 55 + 56) bits

36028797017456641 ,  36028797014704129 ,  36028797014573057 ,  36028797014376449 ,  36028797013327873 ,  36028797013000193 ,  36028797012606977 ,  36028797010444289 ,  36028797009985537 ,  36028797005856769 ,  36028797005529089 ,  36028797005135873 ,  36028797003694081 ,  36028797003563009 ,  36028797001138177 ,  72057594037338113 ,

|   plain_modulus: 786433
\
Save galois key to file.
Load galois key from file.
```

Shouldn't we expect the noise budgets to be some positive numbers?

**Comment by gogo9th** [comment]
Hi, 

I figured out another more concrete issue: the  noise budgets of PhantomFHE ciphertexts seem to be actually lower than those of SEAL ciphertexts, even under the same crypto parameter setup. I found this issue because my software using PhantomFHE does not generate correct results, while everything works correctly when using the original SEAL library. 

Below I create the minimal reproducible example code for this issue: 

```
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <stdlib.h>

using namespace std;
 
#ifdef SEAL
	#include "seal/seal.h"
	using namespace seal;
#elif defined(PHANTOM)
	#include "phantom.h"

	using namespace phantom;
	using namespace phantom::arith;
	using namespace phantom::util;
#endif

int main()
{
	vector<int> coeff_mod_list = {60, 60, 60, 60, 60, 60};

   EncryptionParameters parms(scheme_type::bfv);
	vector<Modulus> mod_list;
	//if (poly_modulus_degree == 16384)
		mod_list = CoeffModulus::Create(16384, coeff_mod_list);
	//else
	//	mod_list = CoeffModulus::BFVDefault(poly_modulus_degree);

   parms.set_poly_modulus_degree(16384);
	parms.set_coeff_modulus(mod_list);
	parms.set_plain_modulus(PlainModulus::Batching(16384, 22));
	#if defined(SEAL) || defined(SEAL_PHANTOM)
		SEALContext context(parms);
		SecretKey sk;
		PublicKey pk;
		RelinKeys relin_keys;
		GaloisKeys gal_keys;
		KeyGenerator keygen(context);
		Evaluator evaluator(context);
		BatchEncoder batch_encoder(context);

		keygen.create_public_key(pk);
		sk = keygen.secret_key();
		stringstream relin_stream, gal_stream;
		keygen.create_relin_keys().save(relin_stream);
		keygen.create_galois_keys().save(gal_stream);
		relin_keys.load(context, relin_stream);
		gal_keys.load(context, gal_stream);
		Encryptor encryptor(context, pk);
		encryptor.set_secret_key(sk); // set it up in the SEAL context
		Decryptor decryptor = Decryptor(context, sk);

	#elif defined(PHANTOM)
		PhantomContext context(parms);
		PhantomSecretKey sk(context);
		PhantomPublicKey pk = sk.gen_publickey(context);
		PhantomRelinKey relin_keys(sk.gen_relinkey(context));
		PhantomGaloisKey gal_keys = sk.create_galois_keys(context);
		PhantomBatchEncoder batch_encoder = PhantomBatchEncoder(context);
	#endif

	vector<uint64_t> vec(16384, 0);
	#if defined(PHANTOM)
		PhantomPlaintext pt;
		PhantomCiphertext ct;
		batch_encoder.encode(context, vec, pt);
		sk.encrypt_symmetric(context, pt, ct);
	#elif defined(SEAL)
		Plaintext pt;
		Ciphertext ct;
		batch_encoder.encode(vec, pt);
		encryptor.encrypt_symmetric(pt, ct);
	#endif
	
	for (int i = 0; i < 4; i++)
	{	cout << "Changing multiplicative chain index from " << i << " -> " << i + 1 << endl;
		#if defined(PHANTOM)
			multiply_inplace(context, ct, ct);
			relinearize_inplace(context, ct, relin_keys);
			mod_switch_to_next_inplace(context, ct);
		#elif defined(SEAL)
			evaluator.multiply_inplace(ct, ct);
			evaluator.relinearize_inplace(ct, relin_keys);
			evaluator.mod_switch_to_next_inplace(ct);
		#endif

		vector<uint64_t> ret_list;
		//assert(this->is_debug);

		#if defined(PHANTOM)
			PhantomPlaintext pt;
			sk.decrypt(context, ct, pt);
			batch_encoder.decode(context, pt, ret_list);
		#elif defined(SEAL)
			Plaintext pt;
			decryptor.decrypt(ct, pt);
			batch_encoder.decode(pt, ret_list);
		#endif	  

		if (ret_list[0] != 0)
		{	cout << "- A decryption error found at multiplicative chain index : " << i << endl;
			exit(0);
		}
	}
	cout << "4 multiplications done successfuly" << endl;
	return 0;
}

```

I also attach the complete source code for this example:
[src.zip](https://github.com/user-attachments/files/17189488/src.zip)

This example assumes that you have installbed both SEAL and PhantomFHE libraries on your Ubuntu 22.04 (or higher) machine. You only need to run:

```
unzip src.zip
cd src/build
cmake .. --fresh -DSEAL=ON # To compile with the SEAL library
make -j
./main   # The 5 consecutive cipher multiplications should work fine

cmake .. --fresh -DPHANTOM=ON # To compile with the PhantomFHE library
make -j
./main   # Only 2 consecutive cipher multiplications will work and the results gets corrupted afterwards
```

**Comment by D4rkCrypto** [comment]
It seems the code for evaluating the noise budget might be broken. I noticed this a while ago as well. I’ll work on fixing it soon.

**Comment by gogo9th** [comment]
Hi, I just got back from CCS 2024 and HE meetup, where Dan Boneh gave a keynote speech about the future of security, where he picked FHE as the first topic. There were also many papers on FHE. So your library is really important for the future of FHE.

Today I tested your update on secret key packing and it works fine. Thanks a lot. Now the only remaining issue is the noise budget issue... Now my application is good enough to demonstrate its speed enhancement by using PhantomFHE (although the correctness does not hold due to the noise budget issue). Hope this one can be also resolved soon :)

**Comment by D4rkCrypto** [comment]
Thanks for testing the update. I’m glad to hear the secret key packing is working well.

I’m currently traveling for work and will be back early next month. I’ll fix the noise budget issue as soon as I return. In the meantime, my colleagues may be able to help.

**Comment by gogo9th** [comment]
Hi, I hope you had a wonderful trip. Just wonder if you had any chance to look into the bug fix...

**Comment by D4rkCrypto** [comment]
Yes, I am working on this, the bug will be fixed soon (maybe today).

**Comment by D4rkCrypto** [comment]
Please check this commit to see if it is working for you now. I have tested it and it is OK.

**Comment by gogo9th** [comment]
Thanks for updating the code and I am sorry for having taken it too long to reply.

There is still some bug in the noise handling, because after the first cipher-cipher multiplication the noise budget suddenly drops to zero:

Noise Budget A: 155
Noise Budget B: 155
Noise Budget A*B: 0

I have been trying to create a minimal reproducible example. Do you have any clue on this?

**Comment by D4rkCrypto** [comment]
I think you didn't do relinearization after multiplication. Current logic of computing noise budget requires the ciphertext size be 2.

**Comment by gogo9th** [comment]
Yes, I am doing relinearization after each multiplication. The code is the same as before. The old version of PhantomFHE worked, but this version does not work..

**Comment by D4rkCrypto** [comment]
I have written an example for testing noise budget and it works fine, pls check here:
https://github.com/encryptorion-lab/phantom-fhe/blob/3bf8833465f897864c514fa7ad2b65c6c3982f76/examples/1_bfv.cu#L1394-L1408

**Comment by gogo9th** [comment]
Hi,

Here I created a minimum reproducible example:

```
#include "phantom.h"

using namespace phantom;
using namespace phantom::arith;
using namespace phantom::util;
using namespace std;

int main(int argc, char* argv[])
{
   EncryptionParameters parms(scheme_type::bfv);

   vector<Modulus> mod_list = CoeffModulus::Create(16384, {60, 60, 60, 60, 60, 60});
   parms.set_poly_modulus_degree(16384);
   parms.set_coeff_modulus(mod_list);
   parms.set_plain_modulus(PlainModulus::Batching(16384, 22));

   PhantomContext context(parms);
   PhantomSecretKey secret_tkey(context);
   PhantomBatchEncoder batch_encoder(context);
   PhantomSecretKey secret_key(context);
   vector<uint64_t> input_slots(16384, 0ULL); // slot_count = poly_mod_degree
   PhantomPlaintext input_pt;
   batch_encoder.encode(context, input_slots, input_pt);

   PhantomCiphertext serial_ct;
   secret_key.encrypt_symmetric(context, input_pt, serial_ct);
   //FHECompressedCiphertext serial_ct = fhe_encrypt_symmetric_compress(input_pt);

   vector<PhantomCiphertext> ct_test_list;
   for (int i = 0; i < 17; i++)
   {  cout << "Add_Many CT[" << i << "] Noise: " << secret_key.invariant_noise_budget(context, serial_ct) << endl;
      ct_test_list.push_back(serial_ct);
   }
   PhantomCiphertext result_ct;
   add_many(context, ct_test_list, result_ct);
   cout << "Add_Many Result Noise : " << secret_key.invariant_noise_budget(context, result_ct) << endl;
}
```

Its output is:
```
Add_Many CT[0] Noise: 273
Add_Many CT[1] Noise: 273
Add_Many CT[2] Noise: 273
Add_Many CT[3] Noise: 273
Add_Many CT[4] Noise: 273
Add_Many CT[5] Noise: 273
Add_Many CT[6] Noise: 273
Add_Many CT[7] Noise: 273
Add_Many CT[8] Noise: 273
Add_Many CT[9] Noise: 273
Add_Many CT[10] Noise: 273
Add_Many CT[11] Noise: 273
Add_Many CT[12] Noise: 273
Add_Many CT[13] Noise: 273
Add_Many CT[14] Noise: 273
Add_Many CT[15] Noise: 273
Add_Many CT[16] Noise: 273
Add_Many Result Noise : 0
```

We expect the final noise to be nearby 273, not 0.

**Comment by D4rkCrypto** [comment]
Fixed. Wrong design in reduction threshold in `add_many` kernel implementation.

**Comment by gogo9th** [comment]
Thanks for the fix. However, the computation results are still not correct, and after some hours of investigation I came up with another minimal reproducible example:

```
#include "phantom.h"

using namespace phantom;
using namespace phantom::arith;
using namespace phantom::util;
using namespace std;

int main()
{  vector<Modulus> mod_list  = CoeffModulus::Create(16384, {60, 60, 60, 60, 60, 60}); 
   unique_ptr<EncryptionParameters> parms = make_unique<EncryptionParameters>(scheme_type::bfv);
   parms->set_poly_modulus_degree(16384);
   parms->set_coeff_modulus(mod_list);
   parms->set_plain_modulus(PlainModulus::Batching(16384, 20));
   
   unique_ptr<PhantomContext> client_context = make_unique<PhantomContext>(*parms);
   unique_ptr<PhantomSecretKey> client_sk = make_unique<PhantomSecretKey>(*client_context);
   unique_ptr<PhantomRelinKey> client_rk = make_unique<PhantomRelinKey>(client_sk->gen_relinkey(*client_context));
   unique_ptr<PhantomBatchEncoder> client_batch_encoder = make_unique<PhantomBatchEncoder>(*client_context);
   
   unique_ptr<PhantomContext> server_context = make_unique<PhantomContext>(*parms);
   unique_ptr<PhantomSecretKey> server_sk = make_unique<PhantomSecretKey>(*server_context);

   vector<uint64_t> input_slots(16384);
   
   stringstream data_stream, sk_stream;
   client_sk->save(sk_stream);
   server_sk->load(sk_stream);
   
   PhantomPlaintext ret_pt;
   PhantomCiphertext ret_ct;
   client_batch_encoder->encode(*client_context, input_slots, ret_pt);
   client_sk->encrypt_symmetric(*client_context, ret_pt, ret_ct);
   cout << "Client's noise before mult_inplace: " << client_sk->invariant_noise_budget(*client_context, ret_ct) << endl; 
   cout << "Server's noise before mult_inplace: " << server_sk->invariant_noise_budget(*server_context, ret_ct) << endl;
   multiply_inplace(*server_context, ret_ct, ret_ct);
   cout << "Client's noise after mult_inplace: " << client_sk->invariant_noise_budget(*client_context, ret_ct) << endl; 
   cout << "Server's noise after mult_inplace: " << server_sk->invariant_noise_budget(*server_context, ret_ct) << endl;
   return 0;
}
```

If I run the above, I get the following output:

```
Client's noise before mult_inplace: 275
Server's noise before mult_inplace: 275
Client's noise after mult_inplace: 243
Server's noise after mult_inplace: 0
```

However, Server's noise after mult_inplace should not be 0. 

If I do not create the relinearization key for the client (`client_rk`), then the output seems fine, which might be a clue for you to fix the bug.

**Comment by D4rkCrypto** [comment]
Thanks a lot for finding the bug and useful clues. This will be fixed soon!

**Comment by gogo9th** [comment]
Hi, I just wonder if you had any chance to look into fixing the issue... Thanks.

**Comment by D4rkCrypto** [comment]
Fixed. Happy new year!

**Comment by gogo9th** [comment]
Thanks very much for your effort to fix the bug, but the issue is still lingering...  I am sorry to take it too long to report the bug again. This was because this time, it was very hard for me to create the minimal reproducible example for you, as my code is quite complex. I get a memory crash while running my program, but this minimal version crashes a memory free error, instead:

```
#include <iostream>
#include <vector>
#include "phantom.h"

using namespace phantom;
using namespace phantom::arith;
using namespace phantom::util;
using namespace std;

shared_ptr<PhantomSecretKey> sk;
unique_ptr<PhantomBatchEncoder> batch_encoder;
unique_ptr<PhantomContext> context;
unique_ptr<PhantomGaloisKey> gal_keys;
unique_ptr<EncryptionParameters> parms;
unique_ptr<PhantomPublicKey> pk;
unique_ptr<PhantomRelinKey> relin_keys;

int main(int argc, char* argv[])
{
   parms = make_unique<EncryptionParameters>(scheme_type::bfv);
   int poly_modulus_degree = 1 << 14;
   int prime_bitlength = 22;

   vector<Modulus> mod_list;
   mod_list = CoeffModulus::Create(poly_modulus_degree, {44, 44, 44, 44, 44, 44});
   parms->set_poly_modulus_degree(poly_modulus_degree);
   parms->set_coeff_modulus(mod_list);
   parms->set_plain_modulus(PlainModulus::Batching(poly_modulus_degree, prime_bitlength));
   context = make_unique<PhantomContext>(*(parms));
   return 0;
}
```

If I run the above code, I get the following 1802 identical error messages:

```
Error freeing 16384 * 8 bytes at 0x302b18800 on stream 0x2
Error code: driver shutting down
```

Could you first try to fix this error? I hope fixing this solves the original memory crash error, as well.. Thanks a lot.

**Comment by D4rkCrypto** [comment]
Hi, sorry for the late reply. Been busy with the new work. I will dig into this bug soon. Thanks for your patience and understanding! Also we will have a major update recently regarding the very first support for CKKS bootstrapping. Pls stay tuned!

**Comment by gogo9th** [comment]
Thanks very much for your update. 

I am very much looking forward to CKKS bootstrapping.
